name: Code Quality Gate
on:
  workflow_dispatch:
  pull_request:
jobs:
    validate_build:
      name: Quality Gate
      runs-on: ubuntu-latest
      steps:
        - name: Checkout git repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.7'
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ./app/requirements.txt
        - name: SonarQube Scan
          uses: kitabisa/sonarqube-action@v1.1.0
          with:
            host: ${{ secrets.SONARQUBE_HOST }}
            login: ${{ secrets.SONARQUBE_TOKEN }}
                 
        - name: wemake-python-styleguide
          uses: wemake-services/wemake-python-styleguide@0.15.2
          with:
            reporter: 'github-pr-review'
            path: './app/'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
